add prefers-color-scheme on offline page
YearInfo/Website pull request #34
Opened 2021-06-22 20:28 UTC by ajhawkings

fixes #31

2021-06-23 10:23 UTC, HandyHat requested changes
Also need to change https://github.com/YearInfo/Website/blob/e206d3279f4d6eaa141fa1815448fbf961b07ba3/sw.js#L16

2021-06-25 19:32 UTC, HandyHat approved these changes

2021-06-25 19:33 UTC, ajhawkings commented
pog

2021-06-25 19:33 UTC, HandyHat requested changes
I think I approved accidentally

Can we change the background to be the same as the main page's background rather than just black

2021-06-25 21:06 UTC, HandyHat requested changes

2021-06-25 21:06 UTC, HandyHat commented on sw/offline.html
> +        background: linear-gradient(90deg, rgb(21, 22, 22) 100%, rgb(0, 13, 19) 0%);
This line is broken - I opened it in VS Code and it instantly started complaining

2021-06-26 07:19 UTC, ajhawkings commented on sw/offline.html
> +        background: linear-gradient(90deg, rgb(21, 22, 22) 100%, rgb(0, 13, 19) 0%);
aaaaaaaaaaaaaaaaaaand this is why you are a reviewer

2021-06-27 14:23 UTC, HandyHat requested changes
wow this is never going to get merged at this rate

2021-06-27 14:23 UTC, HandyHat commented on sw/offline.html
> +      @media (prefers-color-scheme: dark) {
Can we change this to be in line with the main page where it's dark by default unless the browser indicates light instead of vice versa? (backwards compatibility for bad browsers that only get updates with the os...)

2021-06-27 18:22 UTC, ajhawkings commented on sw/offline.html
> +      @media (prefers-color-scheme: dark) {
ookkkkkkkkkkkkkkkkkkkkkkkkkkkk I did it this way because it was light by default before

why do we prioritise dark over light again?

2021-06-29 07:46 UTC, HandyHat approved these changes
pog

2021-06-29 07:49 UTC, HandyHat commented on sw/offline.html
> +      @media (prefers-color-scheme: dark) {
iirc we decided at one point that people in our year prefer dark by far

2021-06-29 07:53 UTC, merged